apiVersion: v1
kind: Service
metadata:
  name: graphql-api-service
spec:
  type: LoadBalancer
  selector:
    app: graphql-api # used to select all pods with the same name select node-app
  ports:
    - port: 4000
      targetPort: 4000
